layout_spectrum: 0.1420792
typography_spectrum: 0.3697438
color:
  saturation: 0.6899201
  lightness: 0.4532858
  brandStrength: 0.2702548
  rhythmicContrast: 0.9756069
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Jonathan Mundy
